# Generated by Django 4.2.2 on 2023-07-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_lead_client_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['id']},
        ),
    ]
