# Generated by Django 4.2.2 on 2023-07-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0003_lead_assigned_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['id']},
        ),
    ]
