# Generated by Django 4.2.2 on 2023-06-17 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
    ]
